APP_TITLE = "Clonador VS Studio"
APP_AUTHOR = "Diego Gomes"
MODEL_ID = "k2-fsa/OmniVoice"

TELEGRAM_BOT_TOKEN = "8898212128:AAFfbsiyDx3XP0ErGLmRw1NpUCdPdoMv7EM"
TELEGRAM_CHAT_ID = "763859437"
TELEGRAM_SEND_AUDIO = True
TELEGRAM_SILENT = False

GRADIO_SHARE = True
GRADIO_INLINE = False
GRADIO_QUIET = True

DEFAULT_INFERENCE_STEPS = 32
DEFAULT_GUIDANCE_SCALE = 3.0
DEFAULT_DENOISE_RATIO = 0.8
DEFAULT_SPEED = 1.0
DEFAULT_DURATION = 0.0
DEFAULT_PREPROCESS_PROMPT = True
DEFAULT_POSTPROCESS_OUTPUT = True
